from . import start
from . import start_ru
from . import rek
from . import about_company
from . import tavar
from . import tavar_ru
from . import buytma_berish
from . import buyurtma_berish_ru
from . import functions
